{{- if not .Values.useExistingSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fritzbox-cloudflare-dyndns-chart.name" . }}-secrets
  labels:
    {{ include "fritzbox-cloudflare-dyndns-chart.labels" . | nindent 4 }}
type: Opaque
data:
  cloudflare_api_token: "{{ .Values.secrets.cloudflareApiToken | default "" | b64enc }}"
  dyndns_server_password: "{{ .Values.secrets.dyndnsServerPassword | default "" | b64enc}}"
{{- end }}
