apiVersion: v1
kind: Service
metadata:
  name: {{ include "fritzbox-cloudflare-dyndns-chart.name" . }}-http
  labels:
    {{ include "fritzbox-cloudflare-dyndns-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{ include "fritzbox-cloudflare-dyndns-chart.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.bindPort }}
      targetPort: http
    {{- if .Values.prometheus.enabled }}
    - name: metrics
      port: 9876
      targetPort: metrics
    {{- end }}
