{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "fritzbox-cloudflare-dyndns-chart.name" .) .Values.serviceAccount.name | trunc 63 | trimSuffix "-" }}
  labels:
    {{ include "fritzbox-cloudflare-dyndns-chart.labels" . | nindent 4 }}
{{- end }}
