{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fritzbox-cloudflare-dyndns-chart.name" . }}-sm
  namespace: {{ .Values.prometheus.namespace }}
  labels:
    release: prometheus
    {{- with .Values.prometheus.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ include "fritzbox-cloudflare-dyndns-chart.name" . }}
  namespaceSelector:
    any: false
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      interval: {{ .Values.prometheus.interval }}
      scrapeTimeout: {{ .Values.prometheus.scrapeTimeout }}
      path: /metrics
{{- end }}
